apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
        version: v1
    spec:
      containers:
        - name: cartservice
          image: registry-vpc.cn-hangzhou.aliyuncs.com/ahas_userone/cartservice:1.0.0
#          image: registry-vpc.cn-hangzhou.aliyuncs.com/ahas_userone/alibaba-micro-cartservice:1.0.0
          imagePullPolicy: Always
          env:
            - name: dubbo.registry.address
              value: "nacos://nacos-server:8848"
            - name: spring.cloud.nacos.discovery.server-addr
              value: "nacos-server:8848"
            - name: spring.cloud.nacos.config.server-addr
              value: "nacos-server:8848"
#            - name: rocketmq.namesrv.addr
#              value: ""
#            - name: rocketmq.consumer.group
#              value: "CID_CART"
#            - name: rocketmq.topic
#              value: "T_CART"
#            - name: rocketmq.tag
#              value: "cart"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-redis
spec:
  selector:
    matchLabels:
      app: cart-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: cart-redis
    spec:
      containers:
        - name: cart-redis
          image: registry.cn-hangzhou.aliyuncs.com/ahas_userone/redis:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: cart-redis
  name: cart-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: cart-redis
